// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: service/proto/slot/slot_op.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlotOpServiceClient is the client API for SlotOpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlotOpServiceClient interface {
	//workerCar RPC
	GetRunWorkerTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*CarWorkerTaskNoInfo, error)
	ModifyCarTaskNo(ctx context.Context, in *CarWorkerTaskNoInfo, opts ...grpc.CallOption) (*ResponseMsg, error)
	AddCarWorkerTaskDetail(ctx context.Context, in *CarWorkerTaskDetailInfo, opts ...grpc.CallOption) (*ResponseMsg, error)
	GetRunCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailInfo, error)
	ModifyCarTaskDetailInfo(ctx context.Context, in *CarWorkerTaskDetailInfo, opts ...grpc.CallOption) (*ResponseMsg, error)
	GetRand(ctx context.Context, in *String, opts ...grpc.CallOption) (*RandList, error)
	GetWaitCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailInfo, error)
	GetAllCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailList, error)
	GetBoostConfig(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	GetMainDisk(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	DistributeWorkerTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	AddCarRand(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	CarFileExist(ctx context.Context, in *SectorID, opts ...grpc.CallOption) (*String, error)
	AddCarFile(ctx context.Context, in *CarFiles, opts ...grpc.CallOption) (*String, error)
}

type slotOpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlotOpServiceClient(cc grpc.ClientConnInterface) SlotOpServiceClient {
	return &slotOpServiceClient{cc}
}

func (c *slotOpServiceClient) GetRunWorkerTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*CarWorkerTaskNoInfo, error) {
	out := new(CarWorkerTaskNoInfo)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetRunWorkerTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) ModifyCarTaskNo(ctx context.Context, in *CarWorkerTaskNoInfo, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, "/SlotOpService/ModifyCarTaskNo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) AddCarWorkerTaskDetail(ctx context.Context, in *CarWorkerTaskDetailInfo, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, "/SlotOpService/AddCarWorkerTaskDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetRunCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailInfo, error) {
	out := new(CarWorkerTaskDetailInfo)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetRunCarTaskDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) ModifyCarTaskDetailInfo(ctx context.Context, in *CarWorkerTaskDetailInfo, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, "/SlotOpService/ModifyCarTaskDetailInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetRand(ctx context.Context, in *String, opts ...grpc.CallOption) (*RandList, error) {
	out := new(RandList)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetRand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetWaitCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailInfo, error) {
	out := new(CarWorkerTaskDetailInfo)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetWaitCarTaskDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetAllCarTaskDetail(ctx context.Context, in *WorkerCarParam, opts ...grpc.CallOption) (*CarWorkerTaskDetailList, error) {
	out := new(CarWorkerTaskDetailList)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetAllCarTaskDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetBoostConfig(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetBoostConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) GetMainDisk(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/GetMainDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) DistributeWorkerTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/DistributeWorkerTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) AddCarRand(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/AddCarRand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) CarFileExist(ctx context.Context, in *SectorID, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/CarFileExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotOpServiceClient) AddCarFile(ctx context.Context, in *CarFiles, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/SlotOpService/AddCarFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlotOpServiceServer is the server API for SlotOpService service.
// All implementations should embed UnimplementedSlotOpServiceServer
// for forward compatibility
type SlotOpServiceServer interface {
	//workerCar RPC
	GetRunWorkerTask(context.Context, *String) (*CarWorkerTaskNoInfo, error)
	ModifyCarTaskNo(context.Context, *CarWorkerTaskNoInfo) (*ResponseMsg, error)
	AddCarWorkerTaskDetail(context.Context, *CarWorkerTaskDetailInfo) (*ResponseMsg, error)
	GetRunCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailInfo, error)
	ModifyCarTaskDetailInfo(context.Context, *CarWorkerTaskDetailInfo) (*ResponseMsg, error)
	GetRand(context.Context, *String) (*RandList, error)
	GetWaitCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailInfo, error)
	GetAllCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailList, error)
	GetBoostConfig(context.Context, *String) (*String, error)
	GetMainDisk(context.Context, *String) (*String, error)
	DistributeWorkerTask(context.Context, *String) (*String, error)
	AddCarRand(context.Context, *String) (*String, error)
	CarFileExist(context.Context, *SectorID) (*String, error)
	AddCarFile(context.Context, *CarFiles) (*String, error)
}

// UnimplementedSlotOpServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSlotOpServiceServer struct {
}

func (UnimplementedSlotOpServiceServer) GetRunWorkerTask(context.Context, *String) (*CarWorkerTaskNoInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunWorkerTask not implemented")
}
func (UnimplementedSlotOpServiceServer) ModifyCarTaskNo(context.Context, *CarWorkerTaskNoInfo) (*ResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyCarTaskNo not implemented")
}
func (UnimplementedSlotOpServiceServer) AddCarWorkerTaskDetail(context.Context, *CarWorkerTaskDetailInfo) (*ResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarWorkerTaskDetail not implemented")
}
func (UnimplementedSlotOpServiceServer) GetRunCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunCarTaskDetail not implemented")
}
func (UnimplementedSlotOpServiceServer) ModifyCarTaskDetailInfo(context.Context, *CarWorkerTaskDetailInfo) (*ResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyCarTaskDetailInfo not implemented")
}
func (UnimplementedSlotOpServiceServer) GetRand(context.Context, *String) (*RandList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRand not implemented")
}
func (UnimplementedSlotOpServiceServer) GetWaitCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaitCarTaskDetail not implemented")
}
func (UnimplementedSlotOpServiceServer) GetAllCarTaskDetail(context.Context, *WorkerCarParam) (*CarWorkerTaskDetailList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCarTaskDetail not implemented")
}
func (UnimplementedSlotOpServiceServer) GetBoostConfig(context.Context, *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoostConfig not implemented")
}
func (UnimplementedSlotOpServiceServer) GetMainDisk(context.Context, *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMainDisk not implemented")
}
func (UnimplementedSlotOpServiceServer) DistributeWorkerTask(context.Context, *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeWorkerTask not implemented")
}
func (UnimplementedSlotOpServiceServer) AddCarRand(context.Context, *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarRand not implemented")
}
func (UnimplementedSlotOpServiceServer) CarFileExist(context.Context, *SectorID) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CarFileExist not implemented")
}
func (UnimplementedSlotOpServiceServer) AddCarFile(context.Context, *CarFiles) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarFile not implemented")
}

// UnsafeSlotOpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlotOpServiceServer will
// result in compilation errors.
type UnsafeSlotOpServiceServer interface {
	mustEmbedUnimplementedSlotOpServiceServer()
}

func RegisterSlotOpServiceServer(s grpc.ServiceRegistrar, srv SlotOpServiceServer) {
	s.RegisterService(&SlotOpService_ServiceDesc, srv)
}

func _SlotOpService_GetRunWorkerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetRunWorkerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetRunWorkerTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetRunWorkerTask(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_ModifyCarTaskNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarWorkerTaskNoInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).ModifyCarTaskNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/ModifyCarTaskNo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).ModifyCarTaskNo(ctx, req.(*CarWorkerTaskNoInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_AddCarWorkerTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarWorkerTaskDetailInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).AddCarWorkerTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/AddCarWorkerTaskDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).AddCarWorkerTaskDetail(ctx, req.(*CarWorkerTaskDetailInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetRunCarTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerCarParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetRunCarTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetRunCarTaskDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetRunCarTaskDetail(ctx, req.(*WorkerCarParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_ModifyCarTaskDetailInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarWorkerTaskDetailInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).ModifyCarTaskDetailInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/ModifyCarTaskDetailInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).ModifyCarTaskDetailInfo(ctx, req.(*CarWorkerTaskDetailInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetRand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetRand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetRand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetRand(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetWaitCarTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerCarParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetWaitCarTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetWaitCarTaskDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetWaitCarTaskDetail(ctx, req.(*WorkerCarParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetAllCarTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerCarParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetAllCarTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetAllCarTaskDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetAllCarTaskDetail(ctx, req.(*WorkerCarParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetBoostConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetBoostConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetBoostConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetBoostConfig(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_GetMainDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).GetMainDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/GetMainDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).GetMainDisk(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_DistributeWorkerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).DistributeWorkerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/DistributeWorkerTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).DistributeWorkerTask(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_AddCarRand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).AddCarRand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/AddCarRand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).AddCarRand(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_CarFileExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SectorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).CarFileExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/CarFileExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).CarFileExist(ctx, req.(*SectorID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotOpService_AddCarFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarFiles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotOpServiceServer).AddCarFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlotOpService/AddCarFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotOpServiceServer).AddCarFile(ctx, req.(*CarFiles))
	}
	return interceptor(ctx, in, info, handler)
}

// SlotOpService_ServiceDesc is the grpc.ServiceDesc for SlotOpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlotOpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SlotOpService",
	HandlerType: (*SlotOpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunWorkerTask",
			Handler:    _SlotOpService_GetRunWorkerTask_Handler,
		},
		{
			MethodName: "ModifyCarTaskNo",
			Handler:    _SlotOpService_ModifyCarTaskNo_Handler,
		},
		{
			MethodName: "AddCarWorkerTaskDetail",
			Handler:    _SlotOpService_AddCarWorkerTaskDetail_Handler,
		},
		{
			MethodName: "GetRunCarTaskDetail",
			Handler:    _SlotOpService_GetRunCarTaskDetail_Handler,
		},
		{
			MethodName: "ModifyCarTaskDetailInfo",
			Handler:    _SlotOpService_ModifyCarTaskDetailInfo_Handler,
		},
		{
			MethodName: "GetRand",
			Handler:    _SlotOpService_GetRand_Handler,
		},
		{
			MethodName: "GetWaitCarTaskDetail",
			Handler:    _SlotOpService_GetWaitCarTaskDetail_Handler,
		},
		{
			MethodName: "GetAllCarTaskDetail",
			Handler:    _SlotOpService_GetAllCarTaskDetail_Handler,
		},
		{
			MethodName: "GetBoostConfig",
			Handler:    _SlotOpService_GetBoostConfig_Handler,
		},
		{
			MethodName: "GetMainDisk",
			Handler:    _SlotOpService_GetMainDisk_Handler,
		},
		{
			MethodName: "DistributeWorkerTask",
			Handler:    _SlotOpService_DistributeWorkerTask_Handler,
		},
		{
			MethodName: "AddCarRand",
			Handler:    _SlotOpService_AddCarRand_Handler,
		},
		{
			MethodName: "CarFileExist",
			Handler:    _SlotOpService_CarFileExist_Handler,
		},
		{
			MethodName: "AddCarFile",
			Handler:    _SlotOpService_AddCarFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/proto/slot/slot_op.proto",
}
